services:
  api:
    build:
      context: .
      dockerfile: ./src/deployment/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - PORT=9000
      - MONGO_DEVELOPMENT=mongodb://mongo:27017/sprocket-factory
    command: sh -c 'npm install && npm run watch'
    networks:
      - api-network

  # Mongo Service
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
      - mongo_config:/data/config
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  mongo_db:
  mongo_config:
